#!/usr/bin/env bash
. ./setup

MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD

rm -rf PyQt5_gpl*

wget -c --no-check-certificate https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-$PYQTVER/PyQt5_gpl-$PYQTVER.tar.gz

tar -zxf PyQt5_gpl-$PYQTVER.tar.gz
rm -rf PyQt5_gpl-$PYQTVER.tar.gz

popd
