#!/usr/bin/env bash
. ./setup

MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD

rm -rf sip-*

wget -c --no-check-certificate https://sourceforge.net/projects/pyqt/files/sip/sip-$SIPVER/sip-$SIPVER.tar.gz

tar -zxf sip-$SIPVER.tar.gz
rm -rf sip-$SIPVER.tar.gz

popd
