#!/usr/bin/env bash
. ./setup

MAYAQTBUILD="`dirname \"$0\"`" # Relative
export MAYAQTBUILD="`( cd \"$MAYAQTBUILD\" && pwd )`" # Absolutized and normalized
pushd $MAYAQTBUILD
 
export SIPDIR=$MAYAQTBUILD/sip-$SIPVER
export MAYA_LOCATION=/usr/autodesk/maya2017
 
pushd $SIPDIR
$MAYA_LOCATION/bin/mayapy ./configure.py
make
sudo make install
popd

popd
